version: '3.8'

services:
  telegram-forwarder:
    build: .
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
      - ./sessions:/app/sessions
      - ./temp:/app/temp
    stdin_open: true  # 启用标准输入
    tty: true        # 分配伪终端
    restart: unless-stopped 